name: tagser
description: A small parser for XML-like documents. 
version: 1.0.3
homepage: https://github.com/Yohanson555/tagser4dart

environment:
  sdk: '>=2.14.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.2
